server:
 port: 8083
mybatis:
 mapper-locations: # 所有的mapper映射文件
 - classpath:mapping/*.xml
spring:
 application:
   name: module-provider  #注册中心显示的应用服务名称
 datasource:
   type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
   driver-class-name: com.mysql.cj.jdbc.Driver  # 配置MySQL的驱动程序类
   url: jdbc:mysql://localhost:3306/springcloud3?serverTimezone=GMT%2B8 # 数据库连接地址
   username: root 	 # 数据库用户名
   password: 123054	 # 数据库连接密码

logging:
  level:
    org.module.provider.mapper: debug


eureka:
  client: # 客户端进行Eureka注册的配置
    register-with-eureka: true
    service-url:
#      defaultZone: http://localhost:7001/eureka
#      defaultZone: http://admin:enjoy@eureka1:7001/eureka
       defaultZone: http://admin:enjoy@eureka1:7001/eureka,http://admin:enjoy@eureka2:7002/eureka,http://admin:enjoy@eureka3:7003/eureka
  instance:
    instance-id: jyz-provider3 # Status栏显示实例名称id
    prefer-ip-address: true   # 左下角链接不再显示主机名，改成显示IP地址
#    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
#    lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒）

# 显示springboot 相关的监控信息
info:
  app.name: module-provider3
  company.name: itest
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$


# spring security 安全相关，统一由module-security模块管理，故此处注释掉
# security:
#   user:
#     name: jyz  # 认证用户名
#     password: jyz  # 认证密码
#     roles:
#      - USER # 授权角色

